<?xml version="1.0" encoding="utf-8"?><Database Name="NutriDataBase" Class="ConectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.SP_Registrar_Nuevo_Usuario" Method="SP_Registrar_Nuevo_Usuario">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Password_Hash" Parameter="password_Hash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Registrar_Feedback" Method="SP_Registrar_Feedback">
    <Parameter Name="Usuario_ID" Parameter="usuario_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Producto_ID" Parameter="producto_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Calificacion" Parameter="calificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Escanear_Codigo" Method="SP_Escanear_Codigo">
    <Parameter Name="Codigo_Barras" Parameter="codigo_Barras" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Eliminar_Usuario" Method="SP_Eliminar_Usuario">
    <Parameter Name="Usuario_ID" Parameter="usuario_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Eliminar_Producto" Method="SP_Eliminar_Producto">
    <Parameter Name="Producto_ID" Parameter="producto_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Eliminar_Feedback" Method="SP_Eliminar_Feedback">
    <Parameter Name="Feedback_ID" Parameter="feedback_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Consultar_Productos_Escaneados" Method="SP_Consultar_Productos_Escaneados">
    <Parameter Name="Usuario_ID" Parameter="usuario_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <ElementType Name="SP_Consultar_Productos_EscaneadosResult">
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Escaneo" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Actualizar_Usuario" Method="SP_Actualizar_Usuario">
    <Parameter Name="Usuario_ID" Parameter="usuario_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Password_Hash" Parameter="password_Hash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Actualizar_Producto" Method="SP_Actualizar_Producto">
    <Parameter Name="Producto_ID" Parameter="producto_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Marca" Parameter="marca" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Informacion_Nutricional" Parameter="informacion_Nutricional" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Iniciar_Sesion" Method="SP_Iniciar_Sesion">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Password_Hash" Parameter="password_Hash" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_HistorialUsuario" Method="SP_HistorialUsuario">
    <Parameter Name="Usuario_ID" Parameter="usuario_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Producto_ID" Parameter="producto_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Exito" Parameter="exito" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Mensaje" Parameter="mensaje" Type="System.String" DbType="NVarChar(255)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>